kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-pv
  labels:
    type: local
    app: mongo-db
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/mongodb/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-db-pv-claim
  labels:
    app: mongo-db
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
