apiVersion: v1
kind: Service
metadata:
  name: mongo-db-service
  labels:
    app: mongo-db
spec:
  type: NodePort
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
      nodePort: 32000
  selector:
    app: mongo-db
