apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db.fullname" . }}
  labels: 
    {{- include "db.labels" . | nindent 4 }}
type: Opague
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=
