apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}
  labels: 
    {{- include "api.labels" . | nindent 4 }}
type: Opague
data:
  API_USERNAME: YWRtaW4=
  API_PASSWORD: cGFzc3dvcmQ=

