api:
  name: api-service
  enabled: true

ui:
  name: ui-service
  enabled: true

db:
  name: no-sql-db
  enabled: true

roles: 
  podApplicationReader: 
    - name: lara
  applicationManager: []
  clusterReader: 
    - name: lara