replicaCount: 3

image:
  repository: localhost:32000/api-service
  tag: v1
  pullPolicy: IfNotPresent

service:
  name: api-service-svc
  type: ClusterIP
  port: 8081

ingress:
  className: "nginx"
  annotations: {
    ingress.kubernetes.io/rewrite-target: /api
  }
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: service.test
      paths:
        - path: /api
          pathType: Prefix
  tls: []