apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels: 
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  # TODO: change to loadbalancer
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    app: {{ template "api.name" . }}
