apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db.fullname" . }}
  label: 
    {{- include "db.labels" . | nindent 4 }}
type: Opague
data:
  MONGO_INITDB_ROOT_USERNAME: test
  MONGO_INITDB_ROOT_PASSWORD: test
