apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ include "k8s.name" . }}-backend-access"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.api.name }}
  policyTypes:
  - Ingress
  - Egress
  ingress: 
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: {{ .Values.db.name }}
      - namespaceSelector:
          matchLabels:
            app.kubernetes.io/name: ingress-nginx
  egress: 
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: {{ .Values.db.name }}
      - namespaceSelector:
          matchLabels:
            app.kubernetes.io/name: ingress-nginx