kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: "test-db-access"
spec:
  podSelector: 
    matchLabels:
      app.kubernetes.io/name: {{ .Values.db.name }}
  policyTypes:
  - Ingress
#   - Egress
    # matchLabels:

  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.api.name }}