apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ include "k8s.name" . }}-frontend-access"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.ui.name }}
  policyTypes:
  - Ingress
  - Egress
  ingress: 
    - from:
      - namespaceSelector:
          matchLabels:
            app.kubernetes.io/name: ingress-nginx