replicaCount: 3

image:
  # Local
  # repository: localhost:32000/api-service
  # Cloud
  repository: europe-west1-docker.pkg.dev/subtle-backup-413213/software-containerization-repo/api-service
  tag: v1
  pullPolicy: IfNotPresent

service:
  name: api-service-svc
  type: ClusterIP
  port: 8081

ingress:
  className: "gce"
  annotations: {
    ingress.kubernetes.io/rewrite-target: /api,
    kubernetes.io/ingress.global-static-ip-name: "web-static-ip",
    kubernetes.io/ingress.class: "gce"
  }
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - paths:
        - path: /api/*
          pathType: ImplementationSpecific
  tls: []