apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: self-signed-ca
spec:
    isCA: true
    commonName: self-signed-ca
    secretName: root-secret
    privateKey:
        algorithm: ECDSA
        size: 256
    issuerRef:
        name: self-signed
        kind: ClusterIssuer
        group: cert-manager.io